### ISSUE TITLE
Suggestion: Renaming "Switch" Button

### ISSUE THREAD

**Issue by jnahan** [ossd-s24/TikTock#10]
I think it could be helpful to rename the "Switch" button to say something like "Break." I found the term "Switch" to be unintuitive and I wasn't sure what the button was for at first.

**Comment by iltenahmet** [comment]
This is a good suggestion. You're welcome to work on this if you'd like. 

I'm thinking the idea would be to change the text every time the button is clicked, back and forth between "break" and "focus". This can be done from the ticktok.js file in the popup directory.

**Comment by jnahan** [comment]
Just made a pull request!

**Comment by iltenahmet** [comment]
#15 is merged now
